
```{r, include = FALSE}
ottrpal::set_knitr_image_path()
```

# ChIP-Seq

## Learning Objectives

```{r, fig.alt = "Learning objectives This chapter will demonstrate how to: Understand the basics of ChIP-Seq data collection and processing workflow. Identify the next steps for your particular ChIP-Seq data. Formulate questions to ask about your ChIP-Seq data", out.width = "100%", echo = FALSE}
ottrpal::include_slide("https://docs.google.com/presentation/d/1YwxXy2rnUgbx_7B7ENH9wpDX-j6JpJz6lGVzOkjo0qY/edit#slide=id.g12890ae15d7_0_61")
```

## What are the goals of ChIP-Seq analysis?

The goal of ChIP-Seq is to....

```{r, fig.alt = "The goal of ChIP-seq is to identify, for a particular DNA binding protein, all of the DNA sequences that it binds to.", out.width = "100%", echo = FALSE}
ottrpal::include_slide("https://docs.google.com/presentation/d/1YwxXy2rnUgbx_7B7ENH9wpDX-j6JpJz6lGVzOkjo0qY/edit#slide=id.g14492c87338_0_18")
```

## ChIP-Seq general workflow overview

## ChIP-Seq data **strengths**:

## ChIP-Seq data **limitations**:

## ChIP-Seq data considerations

## ChiP-seq analysis tools

## More resources about ChiP-seq data
