
# About the Authors {-}

These credits are based on our [course contributors table guidelines](https://github.com/jhudsl/OTTR_Template/wiki/How-to-give-credits).

&nbsp;
&nbsp;

|Credits|Names|
|-------|-----|
|**Pedagogy**||
|Lead Content Instructor(s)|[Candace Savonen]|
|Lecturer(s)|[Candace Savonen]|
|Content Contributor(s)| [Cailin Jordan] - sc-ATAC-Seq, [Carrie Wright], [Claire Mills] - Whole Genome Sequencing, [Jacob Greene] - ChIP-seq |
|Content Directors|[Jeff Leek]|
|Content Consultants|[Carrie Wright], [Cliff Meyer] - ATAC-seq, [Frederick Tan]|
|Acknowledgments||
|**Production**||
|Content Publisher|[Ira Gooding]|
|Content Publishing Reviewers|[Ira Gooding]|
|**Technical**||
|Course Publishing Engineer|[Candace Savonen]|
|Template Publishing Engineers|[Candace Savonen], [Carrie Wright]|
|Publishing Maintenance Engineer|[Candace Savonen]|
|Technical Publishing Stylists|[Carrie Wright], [Candace Savonen]|
|Package Developers ([ottrpal])[Candace Savonen], [John Muschelli], [Carrie Wright]|
|**Art and Design**||
|Illustrator| [Candace Savonen]|
|Figure Artist| [Candace Savonen] and [Claire Mills]|
|Videographer|[Candace Savonen]|
|Videography Editor| [Candace Savonen]|
|**Funding**||
|Funder|[National Cancer Institute (NCI)](https://www.cancer.gov/) UE5 CA254170|
|Funding Staff| [Sandy Ormbrek], [Shasta Nicholson] |

&nbsp;

```{r, echo = FALSE}
devtools::session_info()
```

<!-- Author information -->

[Candace Savonen]: https://www.cansavvy.com/
[Cailin Jordan]: https://www.linkedin.com/in/cailin-jordan-3297b7199/
[Carrie Wright]: https://carriewright11.github.io/
[Claire Mills]: https://www.linkedin.com/in/claire-mills-dds-50883553
[Cliff Meyer]: https://ds.dfci.harvard.edu/our-people/clifford-meyer-phd/
[Ira Gooding]: https://publichealth.jhu.edu/faculty/4130/ira-gooding
[Frederick Tan]: https://bse.carnegiescience.edu/dr-frederick-tan
[Jacob Greene]: https://www.linkedin.com/in/jacob-greene-890aa318a/
[Jeff Leek]: https://jtleek.com/
[John Muschelli]: https://johnmuschelli.com/
[Sandy Ormbrek]: https://hutchdatascience.org/ourteam/
[Shasta Nicholson]: https://hutchdatascience.org/ourteam/

<!-- Links -->

[ottrpal]: https://github.com/jhudsl/ottrpal
